import angular from 'angular';
import 'angular-ui-router'; <% if (ui == 'Angular UI Bootstrap') { %>
import 'angular-ui-bootstrap'; <% } %>

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';

// Import our templates file (generated by Gulp)
import './config/app.templates';

// Import our app functionaity
import './components';
import './services';
import './layout';
import './home';


// Create and bootstrap application
const requires = [
  'ui.router', <% if (ui == 'Angular UI Bootstrap') { %>
  'ui.bootstrap', <% } %>
  'templates',
  'app.components',
  'app.services',
  'app.layout',
  'app.home'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});